version: '3.7'

services:
  cassandra-website:
    build: .
    image: cassandra-website:latest
    volumes:
      - ./src:/usr/src/cassandra-site/src
      - ./content:/usr/src/cassandra-site/publish

  cassandra-website-serve:
    build: .
    image: cassandra-website:latest
    entrypoint: /docker-entrypoint-jekyll-serve.sh
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/src/cassandra-site/src
      - ./content:/usr/src/cassandra-site/publish
      - ./docker-entrypoint-jekyll-serve.sh:/docker-entrypoint-jekyll-serve.sh

  preview:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./content:/usr/share/nginx/html"



